apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow.fullname" . }}
  labels:
    app: {{ template "airflow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  postgresqlUser: {{ .Values.postgresql.postgresqlUser | b64enc | quote }}
  postgresqlPassword: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  redisPassword: {{ .Values.redis.password | b64enc | quote }}
